#!/usr/bin/env bash
#
# Connects an inbound (JNLP) agent to the controller.
#
# The connection secret is generated by Jenkins when it creates the node, so it
# cannot be baked into the image or the compose file. The agent fetches its own
# secret over the REST API instead, which keeps the whole stack reproducible
# from `make up` with no manual copy-paste of a token.
set -euo pipefail

CONTROLLER_URL="${JENKINS_URL:-http://jenkins-controller:8080}"
AGENT_NAME="${JENKINS_AGENT_NAME:-ubuntu-build}"
ADMIN_USER="${JENKINS_ADMIN_ID:-admin}"
ADMIN_PASSWORD="${JENKINS_ADMIN_PASSWORD:-admin}"
WORK_DIR="${JENKINS_AGENT_WORKDIR:-/home/jenkins/agent}"
TIMEOUT="${JENKINS_WAIT_TIMEOUT:-180}"

log() { printf '[agent] %s\n' "$*"; }

log "waiting for ${CONTROLLER_URL}"
deadline=$(( $(date +%s) + TIMEOUT ))
until curl --silent --fail --output /dev/null "${CONTROLLER_URL}/login"; do
    if [[ "$(date +%s)" -ge "${deadline}" ]]; then
        log "controller did not come up within ${TIMEOUT}s"
        exit 1
    fi
    sleep 2
done

log "fetching connection secret for node ${AGENT_NAME}"
secret=""
deadline=$(( $(date +%s) + TIMEOUT ))
while [[ -z "${secret}" ]]; do
    # The .jnlp descriptor carries the secret as the first <argument>.
    secret="$(curl --silent --fail \
        --user "${ADMIN_USER}:${ADMIN_PASSWORD}" \
        "${CONTROLLER_URL}/computer/${AGENT_NAME}/jenkins-agent.jnlp" \
        | sed -n 's:.*<argument>\([a-f0-9]\{32,\}\)</argument>.*:\1:p' | head -1 || true)"

    if [[ -n "${secret}" ]]; then
        break
    fi
    if [[ "$(date +%s)" -ge "${deadline}" ]]; then
        log "could not obtain a secret for ${AGENT_NAME} — is the node defined in casc.yaml?"
        exit 1
    fi
    sleep 2
done

log "connecting as ${AGENT_NAME}"
exec java -jar /usr/share/jenkins-agent.jar \
    -url "${CONTROLLER_URL}" \
    -name "${AGENT_NAME}" \
    -secret "${secret}" \
    -workDir "${WORK_DIR}" \
    -webSocket
